language: c
dist: xenial

git:
  depth: 3

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows

addons:
  artifacts:
    paths:
      - build
  apt:
    packages:
      - gcc-multilib
      - libasound2-dev
      - libxcursor-dev
      - libxinerama-dev
      - mesa-common-dev
      - libx11-dev
      - libxrandr-dev
      - libxrandr2
      - libxi-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev

before_cache:
 - case $TRAVIS_OS_NAME in
     windows)
       $msys2 pacman --sync --clean --noconfirm
       ;;
   esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

before_install:
  - export MAKE=make
  - case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        taskkill //IM gpg-agent.exe //F
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE="$mingw64 make"
        $msys2 pacman -S mingw-w64-x86_64-toolchain
        ;;
    esac
  - mkdir build
  - $RUNNER $CC --version

before_script:

script:
  - $RUNNER $MAKE
  - mv raylua_s build/
  - mv raylua_e build/
