const char *raylua_boot_lua = "--[[" "\n"
"  Copyright (C) 2020 Astie Teddy" "\n"
"" "\n"
"  Permission to use, copy, modify, and/or distribute this software for any" "\n"
"  purpose with or without fee is hereby granted, provided that the above" "\n"
"  copyright notice and this permission notice appear in all copies." "\n"
"" "\n"
"  THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES" "\n"
"  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF" "\n"
"  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR" "\n"
"  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES" "\n"
"  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION" "\n"
"  OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN" "\n"
"  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE." "\n"
"]]" "\n"
"" "\n"
"print \"RAYLUA: Raylua boot script\"" "\n"
"print(\"RAYLUA: Lua Version: \" .. _VERSION)" "\n"
"" "\n"
"if jit then" "\n"
"  print(\"RAYLUA: Lua JIT: \" .. jit.version)" "\n"
"end" "\n"
"" "\n"
"local ffi = require \"ffi\"" "\n"
"local C = ffi.C" "\n"
"" "\n"
"local rl = {}" "\n"
"setmetatable(rl, rl)" "\n"
"" "\n"
"-- structs definition" "\n"
"ffi.cdef [[" "\n"
"  typedef struct Vector2 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"  } Vector2;" "\n"
"" "\n"
"  typedef struct Vector3 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float z;" "\n"
"  } Vector3;" "\n"
"" "\n"
"  typedef struct Vector4 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float z;" "\n"
"    float w;" "\n"
"  } Vector4;" "\n"
"" "\n"
"  typedef Vector4 Quaternion;" "\n"
"" "\n"
"  typedef struct Matrix {" "\n"
"    float m0, m4, m8, m12;" "\n"
"    float m1, m5, m9, m13;" "\n"
"    float m2, m6, m10, m14;" "\n"
"    float m3, m7, m11, m15;" "\n"
"  } Matrix;" "\n"
"" "\n"
"  typedef struct Color {" "\n"
"    unsigned char r;" "\n"
"    unsigned char g;" "\n"
"    unsigned char b;" "\n"
"    unsigned char a;" "\n"
"  } Color;" "\n"
"" "\n"
"  typedef struct Rectangle {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float width;" "\n"
"    float height;" "\n"
"  } Rectangle;" "\n"
"" "\n"
"  typedef struct Image {" "\n"
"    void *data;" "\n"
"    int width;" "\n"
"    int height;" "\n"
"    int mipmaps;" "\n"
"    int format;" "\n"
"  } Image;" "\n"
"" "\n"
"  typedef struct Texture {" "\n"
"    unsigned int id;" "\n"
"    int width;" "\n"
"    int height;" "\n"
"    int mipmaps;" "\n"
"    int format;" "\n"
"  } Texture;" "\n"
"  typedef Texture Texture2D;" "\n"
"  typedef Texture TextureCubemap;" "\n"
"" "\n"
"  typedef struct RenderTexture {" "\n"
"    unsigned int id;" "\n"
"    Texture texture;" "\n"
"    Texture depth;" "\n"
"  } RenderTexture;" "\n"
"  typedef RenderTexture RenderTexture2D;" "\n"
"" "\n"
"  typedef struct NPatchInfo {" "\n"
"    Rectangle sourceRec;" "\n"
"    int left;" "\n"
"    int top;" "\n"
"    int right;" "\n"
"    int bottom;" "\n"
"    int layout;" "\n"
"  } NPatchInfo;" "\n"
"" "\n"
"  typedef struct GlyphInfo {" "\n"
"    int value;" "\n"
"    int offsetX;" "\n"
"    int offsetY;" "\n"
"    int advanceX;" "\n"
"    Image image;" "\n"
"  } GlyphInfo;" "\n"
"" "\n"
"  typedef struct Font {" "\n"
"    int baseSize;" "\n"
"    int glyphCount;" "\n"
"    int glyphPadding;" "\n"
"    Texture2D texture;" "\n"
"    Rectangle *recs;" "\n"
"    GlyphInfo *glyphs;" "\n"
"  } Font;" "\n"
"" "\n"
"  typedef Font SpriteFont;" "\n"
"  typedef struct Camera3D {" "\n"
"    Vector3 position;" "\n"
"    Vector3 target;" "\n"
"    Vector3 up;" "\n"
"    float fovy;" "\n"
"    int projection;" "\n"
"  } Camera3D;" "\n"
"" "\n"
"  typedef Camera3D Camera;" "\n"
"  typedef struct Camera2D {" "\n"
"    Vector2 offset;" "\n"
"    Vector2 target;" "\n"
"    float rotation;" "\n"
"    float zoom;" "\n"
"  } Camera2D;" "\n"
"" "\n"
"  typedef struct Mesh {" "\n"
"    int vertexCount;" "\n"
"    int triangleCount;" "\n"
"    float *vertices;" "\n"
"    float *texcoords;" "\n"
"    float *texcoords2;" "\n"
"    float *normals;" "\n"
"    float *tangents;" "\n"
"    unsigned char *colors;" "\n"
"    unsigned short *indices;" "\n"
"    float *animVertices;" "\n"
"    float *animNormals;" "\n"
"    int *boneIds;" "\n"
"    float *boneWeights;" "\n"
"    unsigned int vaoId;" "\n"
"    unsigned int *vboId;" "\n"
"  } Mesh;" "\n"
"" "\n"
"  typedef struct Shader {" "\n"
"    unsigned int id;" "\n"
"    int *locs;" "\n"
"  } Shader;" "\n"
"" "\n"
"  typedef struct MaterialMap {" "\n"
"    Texture2D texture;" "\n"
"    Color color;" "\n"
"    float value;" "\n"
"  } MaterialMap;" "\n"
"" "\n"
"  typedef struct Material {" "\n"
"    Shader shader;" "\n"
"    MaterialMap *maps;" "\n"
"    float params[4];" "\n"
"  } Material;" "\n"
"" "\n"
"  typedef struct Transform {" "\n"
"    Vector3 translation;" "\n"
"    Quaternion rotation;" "\n"
"    Vector3 scale;" "\n"
"  } Transform;" "\n"
"" "\n"
"  typedef struct BoneInfo {" "\n"
"    char name[32];" "\n"
"    int parent;" "\n"
"  } BoneInfo;" "\n"
"" "\n"
"  typedef struct Model {" "\n"
"    Matrix transform;" "\n"
"" "\n"
"    int meshCount;" "\n"
"" "\n"
"    int materialCount;" "\n"
"    Mesh *meshes;" "\n"
"    Material *materials;" "\n"
"    int *meshMaterial;" "\n"
"    int boneCount;" "\n"
"    BoneInfo *bones;" "\n"
"    Transform *bindPose;" "\n"
"  } Model;" "\n"
"" "\n"
"  typedef struct ModelAnimation {" "\n"
"    int boneCount;" "\n"
"    int frameCount;" "\n"
"    BoneInfo *bones;" "\n"
"    Transform **framePoses;" "\n"
"    char name[32];" "\n"
"  } ModelAnimation;" "\n"
"" "\n"
"  typedef struct Ray {" "\n"
"    Vector3 position;" "\n"
"    Vector3 direction;" "\n"
"  } Ray;" "\n"
"" "\n"
"  typedef struct RayCollision {" "\n"
"    bool hit;" "\n"
"    float distance;" "\n"
"    Vector3 point;" "\n"
"    Vector3 normal;" "\n"
"  } RayCollision;" "\n"
"" "\n"
"  typedef struct BoundingBox {" "\n"
"    Vector3 min;" "\n"
"    Vector3 max;" "\n"
"  } BoundingBox;" "\n"
"" "\n"
"  typedef struct Wave {" "\n"
"    unsigned int frameCount;" "\n"
"    unsigned int sampleRate;" "\n"
"    unsigned int sampleSize;" "\n"
"    unsigned int channels;" "\n"
"    void *data;" "\n"
"  } Wave;" "\n"
"" "\n"
"  typedef struct rAudioBuffer rAudioBuffer;" "\n"
"  typedef struct rAudioProcessor rAudioProcessor;" "\n"
"" "\n"
"  typedef struct AudioStream {" "\n"
"    rAudioBuffer *buffer;" "\n"
"    rAudioProcessor *processor;" "\n"
"" "\n"
"    unsigned int sampleRate;" "\n"
"    unsigned int sampleSize;" "\n"
"    unsigned int channels;" "\n"
"  } AudioStream;" "\n"
"" "\n"
"  typedef struct Sound {" "\n"
"    AudioStream stream;" "\n"
"    unsigned int frameCount;" "\n"
"  } Sound;" "\n"
"" "\n"
"  typedef struct Music {" "\n"
"    AudioStream stream;" "\n"
"    unsigned int frameCount;" "\n"
"    bool looping;" "\n"
"" "\n"
"    int ctxType;" "\n"
"    void *ctxData;" "\n"
"  } Music;" "\n"
"" "\n"
"  typedef struct VrDeviceInfo {" "\n"
"    int hResolution;" "\n"
"    int vResolution;" "\n"
"    float hScreenSize;" "\n"
"    float vScreenSize;" "\n"
"    float vScreenCenter;" "\n"
"    float eyeToScreenDistance;" "\n"
"    float lensSeparationDistance;" "\n"
"    float interpupillaryDistance;" "\n"
"    float lensDistortionValues[4];" "\n"
"    float chromaAbCorrection[4];" "\n"
"  } VrDeviceInfo;" "\n"
"" "\n"
"  typedef struct VrStereoConfig {" "\n"
"    Matrix projection[2];" "\n"
"    Matrix viewOffset[2];" "\n"
"    float leftLensCenter[2];" "\n"
"    float rightLensCenter[2];" "\n"
"    float leftScreenCenter[2];" "\n"
"    float rightScreenCenter[2];" "\n"
"    float scale[2];" "\n"
"    float scaleIn[2];" "\n"
"  } VrStereoConfig;" "\n"
"" "\n"
"  typedef struct FilePathList {" "\n"
"    unsigned int capacity;" "\n"
"    unsigned int count;" "\n"
"    char **paths;" "\n"
"  } FilePathList;" "\n"
"" "\n"
"  typedef struct AutomationEvent {" "\n"
"    unsigned int frame;" "\n"
"    unsigned int type;" "\n"
"    int params[4];" "\n"
"  } AutomationEvent;" "\n"
"  " "\n"
"  typedef struct AutomationEventList {" "\n"
"    unsigned int capacity;" "\n"
"    unsigned int count;" "\n"
"    AutomationEvent *events;" "\n"
"  } AutomationEventList;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    FLAG_VSYNC_HINT = 0x00000040," "\n"
"    FLAG_FULLSCREEN_MODE = 0x00000002," "\n"
"    FLAG_WINDOW_RESIZABLE = 0x00000004," "\n"
"    FLAG_WINDOW_UNDECORATED = 0x00000008," "\n"
"    FLAG_WINDOW_HIDDEN = 0x00000080," "\n"
"    FLAG_WINDOW_MINIMIZED = 0x00000200," "\n"
"    FLAG_WINDOW_MAXIMIZED = 0x00000400," "\n"
"    FLAG_WINDOW_UNFOCUSED = 0x00000800," "\n"
"    FLAG_WINDOW_TOPMOST = 0x00001000," "\n"
"    FLAG_WINDOW_ALWAYS_RUN = 0x00000100," "\n"
"    FLAG_WINDOW_TRANSPARENT = 0x00000010," "\n"
"    FLAG_WINDOW_HIGHDPI = 0x00002000," "\n"
"    FLAG_WINDOW_MOUSE_PASSTHROUGH = 0x00004000," "\n"
"    FLAG_BORDERLESS_WINDOWED_MODE = 0x00008000," "\n"
"    FLAG_MSAA_4X_HINT = 0x00000020," "\n"
"    FLAG_INTERLACED_HINT = 0x00010000" "\n"
"  } ConfigFlags;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    LOG_ALL = 0," "\n"
"    LOG_TRACE," "\n"
"    LOG_DEBUG," "\n"
"    LOG_INFO," "\n"
"    LOG_WARNING," "\n"
"    LOG_ERROR," "\n"
"    LOG_FATAL," "\n"
"    LOG_NONE" "\n"
"  } TraceLogLevel;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    KEY_NULL = 0," "\n"
"    KEY_APOSTROPHE = 39," "\n"
"    KEY_COMMA = 44," "\n"
"    KEY_MINUS = 45," "\n"
"    KEY_PERIOD = 46," "\n"
"    KEY_SLASH = 47," "\n"
"    KEY_ZERO = 48," "\n"
"    KEY_ONE = 49," "\n"
"    KEY_TWO = 50," "\n"
"    KEY_THREE = 51," "\n"
"    KEY_FOUR = 52," "\n"
"    KEY_FIVE = 53," "\n"
"    KEY_SIX = 54," "\n"
"    KEY_SEVEN = 55," "\n"
"    KEY_EIGHT = 56," "\n"
"    KEY_NINE = 57," "\n"
"    KEY_SEMICOLON = 59," "\n"
"    KEY_EQUAL = 61," "\n"
"    KEY_A = 65," "\n"
"    KEY_B = 66," "\n"
"    KEY_C = 67," "\n"
"    KEY_D = 68," "\n"
"    KEY_E = 69," "\n"
"    KEY_F = 70," "\n"
"    KEY_G = 71," "\n"
"    KEY_H = 72," "\n"
"    KEY_I = 73," "\n"
"    KEY_J = 74," "\n"
"    KEY_K = 75," "\n"
"    KEY_L = 76," "\n"
"    KEY_M = 77," "\n"
"    KEY_N = 78," "\n"
"    KEY_O = 79," "\n"
"    KEY_P = 80," "\n"
"    KEY_Q = 81," "\n"
"    KEY_R = 82," "\n"
"    KEY_S = 83," "\n"
"    KEY_T = 84," "\n"
"    KEY_U = 85," "\n"
"    KEY_V = 86," "\n"
"    KEY_W = 87," "\n"
"    KEY_X = 88," "\n"
"    KEY_Y = 89," "\n"
"    KEY_Z = 90," "\n"
"    KEY_LEFT_BRACKET = 91," "\n"
"    KEY_BACKSLASH = 92," "\n"
"    KEY_RIGHT_BRACKET = 93," "\n"
"    KEY_GRAVE = 96," "\n"
"    KEY_SPACE = 32," "\n"
"    KEY_ESCAPE = 256," "\n"
"    KEY_ENTER = 257," "\n"
"    KEY_TAB = 258," "\n"
"    KEY_BACKSPACE = 259," "\n"
"    KEY_INSERT= 260," "\n"
"    KEY_DELETE= 261," "\n"
"    KEY_RIGHT = 262," "\n"
"    KEY_LEFT = 263," "\n"
"    KEY_DOWN = 264," "\n"
"    KEY_UP = 265," "\n"
"    KEY_PAGE_UP = 266," "\n"
"    KEY_PAGE_DOWN = 267," "\n"
"    KEY_HOME = 268," "\n"
"    KEY_END = 269," "\n"
"    KEY_CAPS_LOCK = 280," "\n"
"    KEY_SCROLL_LOCK = 281," "\n"
"    KEY_NUM_LOCK = 282," "\n"
"    KEY_PRINT_SCREEN = 283," "\n"
"    KEY_PAUSE = 284," "\n"
"    KEY_F1 = 290," "\n"
"    KEY_F2 = 291," "\n"
"    KEY_F3 = 292," "\n"
"    KEY_F4 = 293," "\n"
"    KEY_F5 = 294," "\n"
"    KEY_F6 = 295," "\n"
"    KEY_F7 = 296," "\n"
"    KEY_F8 = 297," "\n"
"    KEY_F9 = 298," "\n"
"    KEY_F10 = 299," "\n"
"    KEY_F11 = 300," "\n"
"    KEY_F12 = 301," "\n"
"    KEY_LEFT_SHIFT = 340," "\n"
"    KEY_LEFT_CONTROL = 341," "\n"
"    KEY_LEFT_ALT = 342," "\n"
"    KEY_LEFT_SUPER = 343," "\n"
"    KEY_RIGHT_SHIFT = 344," "\n"
"    KEY_RIGHT_CONTROL = 345," "\n"
"    KEY_RIGHT_ALT = 346," "\n"
"    KEY_RIGHT_SUPER = 347," "\n"
"    KEY_KB_MENU = 348," "\n"
"    KEY_KP_0 = 320," "\n"
"    KEY_KP_1 = 321," "\n"
"    KEY_KP_2 = 322," "\n"
"    KEY_KP_3 = 323," "\n"
"    KEY_KP_4 = 324," "\n"
"    KEY_KP_5 = 325," "\n"
"    KEY_KP_6 = 326," "\n"
"    KEY_KP_7 = 327," "\n"
"    KEY_KP_8 = 328," "\n"
"    KEY_KP_9 = 329," "\n"
"    KEY_KP_DECIMAL = 330," "\n"
"    KEY_KP_DIVIDE = 331," "\n"
"    KEY_KP_MULTIPLY = 332," "\n"
"    KEY_KP_SUBTRACT = 333," "\n"
"    KEY_KP_ADD = 334," "\n"
"    KEY_KP_ENTER = 335," "\n"
"    KEY_KP_EQUAL = 336," "\n"
"    /* Android key buttons */" "\n"
"    KEY_BACK = 4," "\n"
"    KEY_MENU = 82," "\n"
"    KEY_VOLUME_UP = 24," "\n"
"    KEY_VOLUME_DOWN = 25" "\n"
"  } KeyboardKey;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    MOUSE_BUTTON_LEFT = 0," "\n"
"    MOUSE_BUTTON_RIGHT = 1," "\n"
"    MOUSE_BUTTON_MIDDLE = 2," "\n"
"    MOUSE_BUTTON_SIDE = 3," "\n"
"    MOUSE_BUTTON_EXTRA = 4," "\n"
"    MOUSE_BUTTON_FORWARD = 5," "\n"
"    MOUSE_BUTTON_BACK = 6" "\n"
"  } MouseButton;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    MOUSE_CURSOR_DEFAULT = 0," "\n"
"    MOUSE_CURSOR_ARROW = 1," "\n"
"    MOUSE_CURSOR_IBEAM = 2," "\n"
"    MOUSE_CURSOR_CROSSHAIR = 3," "\n"
"    MOUSE_CURSOR_POINTING_HAND = 4," "\n"
"    MOUSE_CURSOR_RESIZE_EW = 5," "\n"
"    MOUSE_CURSOR_RESIZE_NS = 6," "\n"
"    MOUSE_CURSOR_RESIZE_NWSE = 7," "\n"
"    MOUSE_CURSOR_RESIZE_NESW = 8," "\n"
"    MOUSE_CURSOR_RESIZE_ALL = 9," "\n"
"    MOUSE_CURSOR_NOT_ALLOWED = 10" "\n"
"  } MouseCursor;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GAMEPAD_BUTTON_UNKNOWN = 0," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_UP," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_RIGHT," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_DOWN," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_LEFT," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_UP," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_DOWN," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_LEFT," "\n"
"    GAMEPAD_BUTTON_LEFT_TRIGGER_1," "\n"
"    GAMEPAD_BUTTON_LEFT_TRIGGER_2," "\n"
"    GAMEPAD_BUTTON_RIGHT_TRIGGER_1," "\n"
"    GAMEPAD_BUTTON_RIGHT_TRIGGER_2," "\n"
"    GAMEPAD_BUTTON_MIDDLE_LEFT," "\n"
"    GAMEPAD_BUTTON_MIDDLE," "\n"
"    GAMEPAD_BUTTON_MIDDLE_RIGHT," "\n"
"    GAMEPAD_BUTTON_LEFT_THUMB," "\n"
"    GAMEPAD_BUTTON_RIGHT_THUMB" "\n"
"  } GamepadButton;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GAMEPAD_AXIS_UNKNOWN = 0," "\n"
"    GAMEPAD_AXIS_LEFT_X," "\n"
"    GAMEPAD_AXIS_LEFT_Y," "\n"
"    GAMEPAD_AXIS_RIGHT_X," "\n"
"    GAMEPAD_AXIS_RIGHT_Y," "\n"
"    GAMEPAD_AXIS_LEFT_TRIGGER," "\n"
"    GAMEPAD_AXIS_RIGHT_TRIGGER" "\n"
"  } GamepadAxis;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    MATERIAL_MAP_ALBEDO = 0," "\n"
"    MATERIAL_MAP_METALNESS," "\n"
"    MATERIAL_MAP_NORMAL," "\n"
"    MATERIAL_MAP_ROUGHNESS," "\n"
"    MATERIAL_MAP_OCCLUSION," "\n"
"    MATERIAL_MAP_EMISSION," "\n"
"    MATERIAL_MAP_HEIGHT," "\n"
"    MATERIAL_MAP_CUBEMAP," "\n"
"    MATERIAL_MAP_IRRADIANCE," "\n"
"    MATERIAL_MAP_PREFILTER," "\n"
"    MATERIAL_MAP_BRDF," "\n"
"  } MaterialMapIndex;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SHADER_LOC_VERTEX_POSITION = 0," "\n"
"    SHADER_LOC_VERTEX_TEXCOORD01," "\n"
"    SHADER_LOC_VERTEX_TEXCOORD02," "\n"
"    SHADER_LOC_VERTEX_NORMAL," "\n"
"    SHADER_LOC_VERTEX_TANGENT," "\n"
"    SHADER_LOC_VERTEX_COLOR," "\n"
"    SHADER_LOC_MATRIX_MVP," "\n"
"    SHADER_LOC_MATRIX_VIEW," "\n"
"    SHADER_LOC_MATRIX_PROJECTION," "\n"
"    SHADER_LOC_MATRIX_MODEL," "\n"
"    SHADER_LOC_MATRIX_NORMAL," "\n"
"    SHADER_LOC_VECTOR_VIEW," "\n"
"    SHADER_LOC_COLOR_DIFFUSE," "\n"
"    SHADER_LOC_COLOR_SPECULAR," "\n"
"    SHADER_LOC_COLOR_AMBIENT," "\n"
"    SHADER_LOC_MAP_ALBEDO," "\n"
"    SHADER_LOC_MAP_METALNESS," "\n"
"    SHADER_LOC_MAP_NORMAL," "\n"
"    SHADER_LOC_MAP_ROUGHNESS," "\n"
"    SHADER_LOC_MAP_OCCLUSION," "\n"
"    SHADER_LOC_MAP_EMISSION," "\n"
"    SHADER_LOC_MAP_HEIGHT," "\n"
"    SHADER_LOC_MAP_CUBEMAP," "\n"
"    SHADER_LOC_MAP_IRRADIANCE," "\n"
"    SHADER_LOC_MAP_PREFILTER," "\n"
"    SHADER_LOC_MAP_BRDF" "\n"
"  } ShaderLocationIndex;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SHADER_UNIFORM_FLOAT = 0," "\n"
"    SHADER_UNIFORM_VEC2," "\n"
"    SHADER_UNIFORM_VEC3," "\n"
"    SHADER_UNIFORM_VEC4," "\n"
"    SHADER_UNIFORM_INT," "\n"
"    SHADER_UNIFORM_IVEC2," "\n"
"    SHADER_UNIFORM_IVEC3," "\n"
"    SHADER_UNIFORM_IVEC4," "\n"
"    SHADER_UNIFORM_SAMPLER2D" "\n"
"  } ShaderUniformDataType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SHADER_ATTRIB_FLOAT = 0," "\n"
"    SHADER_ATTRIB_VEC2," "\n"
"    SHADER_ATTRIB_VEC3," "\n"
"    SHADER_ATTRIB_VEC4" "\n"
"  } ShaderAttributeDataType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1," "\n"
"    PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R5G6B5," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R8G8B8," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R5G5B5A1," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R4G4B4A4," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R8G8B8A8," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R32," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R32G32B32," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R32G32B32A32," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R16," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R16G16B16," "\n"
"    PIXELFORMAT_UNCOMPRESSED_R16G16B16A16," "\n"
"    PIXELFORMAT_COMPRESSED_DXT1_RGB," "\n"
"    PIXELFORMAT_COMPRESSED_DXT1_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_DXT3_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_DXT5_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_ETC1_RGB," "\n"
"    PIXELFORMAT_COMPRESSED_ETC2_RGB," "\n"
"    PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_PVRT_RGB," "\n"
"    PIXELFORMAT_COMPRESSED_PVRT_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA," "\n"
"    PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA" "\n"
"  } PixelFormat;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXTURE_FILTER_POINT = 0," "\n"
"    TEXTURE_FILTER_BILINEAR," "\n"
"    TEXTURE_FILTER_TRILINEAR," "\n"
"    TEXTURE_FILTER_ANISOTROPIC_4X," "\n"
"    TEXTURE_FILTER_ANISOTROPIC_8X," "\n"
"    TEXTURE_FILTER_ANISOTROPIC_16X," "\n"
"  } TextureFilter;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXTURE_WRAP_REPEAT = 0," "\n"
"    TEXTURE_WRAP_CLAMP," "\n"
"    TEXTURE_WRAP_MIRROR_REPEAT," "\n"
"    TEXTURE_WRAP_MIRROR_CLAMP" "\n"
"  } TextureWrapMode;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    CUBEMAP_LAYOUT_AUTO_DETECT = 0," "\n"
"    CUBEMAP_LAYOUT_LINE_VERTICAL," "\n"
"    CUBEMAP_LAYOUT_LINE_HORIZONTAL," "\n"
"    CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR," "\n"
"    CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE," "\n"
"    CUBEMAP_LAYOUT_PANORAMA" "\n"
"  } CubemapLayout;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    FONT_DEFAULT = 0," "\n"
"    FONT_BITMAP," "\n"
"    FONT_SDF" "\n"
"  } FontType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    BLEND_ALPHA = 0," "\n"
"    BLEND_ADDITIVE," "\n"
"    BLEND_MULTIPLIED," "\n"
"    BLEND_ADD_COLORS," "\n"
"    BLEND_SUBTRACT_COLORS," "\n"
"    BLEND_ALPHA_PREMULTIPLY," "\n"
"    BLEND_CUSTOM," "\n"
"    BLEND_CUSTOM_SEPARATE" "\n"
"  } BlendMode;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GESTURE_NONE = 0," "\n"
"    GESTURE_TAP = 1," "\n"
"    GESTURE_DOUBLETAP = 2," "\n"
"    GESTURE_HOLD = 4," "\n"
"    GESTURE_DRAG = 8," "\n"
"    GESTURE_SWIPE_RIGHT = 16," "\n"
"    GESTURE_SWIPE_LEFT = 32," "\n"
"    GESTURE_SWIPE_UP = 64," "\n"
"    GESTURE_SWIPE_DOWN = 128," "\n"
"    GESTURE_PINCH_IN = 256," "\n"
"    GESTURE_PINCH_OUT = 512" "\n"
"  } Gesture;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    CAMERA_CUSTOM = 0," "\n"
"    CAMERA_FREE," "\n"
"    CAMERA_ORBITAL," "\n"
"    CAMERA_FIRST_PERSON," "\n"
"    CAMERA_THIRD_PERSON" "\n"
"  } CameraMode;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    CAMERA_PERSPECTIVE = 0," "\n"
"    CAMERA_ORTHOGRAPHIC" "\n"
"  } CameraProjection;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    NPATCH_NINE_PATCH = 0," "\n"
"    NPATCH_THREE_PATCH_VERTICAL," "\n"
"    NPATCH_THREE_PATCH_HORIZONTAL" "\n"
"  } NPatchLayout;" "\n"
"" "\n"
"  typedef void (*TraceLogCallback)(int logLevel, const char *text, va_list args);" "\n"
"  typedef void (*AudioCallback)(void *bufferData, unsigned int frames);" "\n"
"]]" "\n"
"" "\n"
"-- raymath cdef" "\n"
"ffi.cdef [[" "\n"
"  typedef struct float3 { float v[3]; } float3;" "\n"
"  typedef struct float16 { float v[16]; } float16;" "\n"
"]]" "\n"
"" "\n"
"-- rlgl cdef" "\n"
"ffi.cdef [[" "\n"
"  typedef enum {" "\n"
"    RL_OPENGL_11 = 1," "\n"
"    RL_OPENGL_21," "\n"
"    RL_OPENGL_33," "\n"
"    RL_OPENGL_43," "\n"
"    RL_OPENGL_ES_20," "\n"
"    RL_OPENGL_ES_30" "\n"
"  } rlGlVersion;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_LOG_ALL = 0," "\n"
"    RL_LOG_TRACE," "\n"
"    RL_LOG_DEBUG," "\n"
"    RL_LOG_INFO," "\n"
"    RL_LOG_WARNING," "\n"
"    RL_LOG_ERROR," "\n"
"    RL_LOG_FATAL," "\n"
"    RL_LOG_NONE" "\n"
"  } rlTraceLogLevel;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R32," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R16," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16," "\n"
"    RL_PIXELFORMAT_UNCOMPRESSED_R16G16B16A16," "\n"
"    RL_PIXELFORMAT_COMPRESSED_DXT1_RGB," "\n"
"    RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_ETC1_RGB," "\n"
"    RL_PIXELFORMAT_COMPRESSED_ETC2_RGB," "\n"
"    RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_PVRT_RGB," "\n"
"    RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA," "\n"
"    RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA" "\n"
"  } rlPixelFormat;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_TEXTURE_FILTER_POINT = 0," "\n"
"    RL_TEXTURE_FILTER_BILINEAR," "\n"
"    RL_TEXTURE_FILTER_TRILINEAR," "\n"
"    RL_TEXTURE_FILTER_ANISOTROPIC_4X," "\n"
"    RL_TEXTURE_FILTER_ANISOTROPIC_8X," "\n"
"    RL_TEXTURE_FILTER_ANISOTROPIC_16X," "\n"
"  } rlTextureFilter;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_BLEND_ALPHA = 0," "\n"
"    RL_BLEND_ADDITIVE," "\n"
"    RL_BLEND_MULTIPLIED," "\n"
"    RL_BLEND_ADD_COLORS," "\n"
"    RL_BLEND_SUBTRACT_COLORS," "\n"
"    RL_BLEND_ALPHA_PREMULTIPLY," "\n"
"    RL_BLEND_CUSTOM" "\n"
"  } rlBlendMode;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_SHADER_LOC_VERTEX_POSITION = 0," "\n"
"    RL_SHADER_LOC_VERTEX_TEXCOORD01," "\n"
"    RL_SHADER_LOC_VERTEX_TEXCOORD02," "\n"
"    RL_SHADER_LOC_VERTEX_NORMAL," "\n"
"    RL_SHADER_LOC_VERTEX_TANGENT," "\n"
"    RL_SHADER_LOC_VERTEX_COLOR," "\n"
"    RL_SHADER_LOC_MATRIX_MVP," "\n"
"    RL_SHADER_LOC_MATRIX_VIEW," "\n"
"    RL_SHADER_LOC_MATRIX_PROJECTION," "\n"
"    RL_SHADER_LOC_MATRIX_MODEL," "\n"
"    RL_SHADER_LOC_MATRIX_NORMAL," "\n"
"    RL_SHADER_LOC_VECTOR_VIEW," "\n"
"    RL_SHADER_LOC_COLOR_DIFFUSE," "\n"
"    RL_SHADER_LOC_COLOR_SPECULAR," "\n"
"    RL_SHADER_LOC_COLOR_AMBIENT," "\n"
"    RL_SHADER_LOC_MAP_ALBEDO," "\n"
"    RL_SHADER_LOC_MAP_METALNESS," "\n"
"    RL_SHADER_LOC_MAP_NORMAL," "\n"
"    RL_SHADER_LOC_MAP_ROUGHNESS," "\n"
"    RL_SHADER_LOC_MAP_OCCLUSION," "\n"
"    RL_SHADER_LOC_MAP_EMISSION," "\n"
"    RL_SHADER_LOC_MAP_HEIGHT," "\n"
"    RL_SHADER_LOC_MAP_CUBEMAP," "\n"
"    RL_SHADER_LOC_MAP_IRRADIANCE," "\n"
"    RL_SHADER_LOC_MAP_PREFILTER," "\n"
"    RL_SHADER_LOC_MAP_BRDF" "\n"
"  } rlShaderLocationIndex;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_SHADER_UNIFORM_FLOAT = 0," "\n"
"    RL_SHADER_UNIFORM_VEC2," "\n"
"    RL_SHADER_UNIFORM_VEC3," "\n"
"    RL_SHADER_UNIFORM_VEC4," "\n"
"    RL_SHADER_UNIFORM_INT," "\n"
"    RL_SHADER_UNIFORM_IVEC2," "\n"
"    RL_SHADER_UNIFORM_IVEC3," "\n"
"    RL_SHADER_UNIFORM_IVEC4," "\n"
"    RL_SHADER_UNIFORM_SAMPLER2D" "\n"
"  } rlShaderUniformDataType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_SHADER_ATTRIB_FLOAT = 0," "\n"
"    RL_SHADER_ATTRIB_VEC2," "\n"
"    RL_SHADER_ATTRIB_VEC3," "\n"
"    RL_SHADER_ATTRIB_VEC4" "\n"
"  } rlShaderAttributeDataType;" "\n"
"  " "\n"
"  typedef enum {" "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL0 = 0," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL1 = 1," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL2 = 2," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL3 = 3," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL4 = 4," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL5 = 5," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL6 = 6," "\n"
"    RL_ATTACHMENT_COLOR_CHANNEL7 = 7," "\n"
"    RL_ATTACHMENT_DEPTH = 100," "\n"
"    RL_ATTACHMENT_STENCIL = 200," "\n"
"  } rlFramebufferAttachType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_ATTACHMENT_CUBEMAP_POSITIVE_X = 0," "\n"
"    RL_ATTACHMENT_CUBEMAP_NEGATIVE_X = 1," "\n"
"    RL_ATTACHMENT_CUBEMAP_POSITIVE_Y = 2," "\n"
"    RL_ATTACHMENT_CUBEMAP_NEGATIVE_Y = 3," "\n"
"    RL_ATTACHMENT_CUBEMAP_POSITIVE_Z = 4," "\n"
"    RL_ATTACHMENT_CUBEMAP_NEGATIVE_Z = 5," "\n"
"    RL_ATTACHMENT_TEXTURE2D = 100," "\n"
"    RL_ATTACHMENT_RENDERBUFFER = 200," "\n"
"  } rlFramebufferAttachTextureType;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    RL_CULL_FACE_FRONT = 0," "\n"
"    RL_CULL_FACE_BACK" "\n"
"  } rlCullMode;" "\n"
"" "\n"
"  /* NOTE: Assumes non-ES OpenGL. */" "\n"
"  typedef struct rlVertexBuffer {" "\n"
"    int elementCount;" "\n"
"" "\n"
"    float *vertices;" "\n"
"    float *texcoords;" "\n"
"    unsigned char *colors;" "\n"
"    unsigned int *indices;" "\n"
"" "\n"
"    unsigned int vaoId;" "\n"
"    unsigned int vboId[4];" "\n"
"  } rlVertexBuffer;" "\n"
"" "\n"
"  typedef struct rlDrawCall {" "\n"
"    int mode;" "\n"
"    int vertexCount;" "\n"
"    int vertexAlignment;" "\n"
"    //unsigned int vaoId;" "\n"
"    //unsigned int shaderId;" "\n"
"    unsigned int textureId;" "\n"
"" "\n"
"    //Matrix projection;" "\n"
"    //Matrix modelview;" "\n"
"  } rlDrawCall;" "\n"
"" "\n"
"  typedef struct rlRenderBatch {" "\n"
"    int bufferCount;" "\n"
"    int currentBuffer;" "\n"
"    rlVertexBuffer *vertexBuffer;" "\n"
"" "\n"
"    rlDrawCall *draws;" "\n"
"    int drawCounter;" "\n"
"    float currentDepth;" "\n"
"  } rlRenderBatch;" "\n"
"]]" "\n"
"" "\n"
"-- rlgl defines" "\n"
"rl.RL_TEXTURE_WRAP_S = 0x2802" "\n"
"rl.RL_TEXTURE_WRAP_T = 0x2803" "\n"
"rl.RL_TEXTURE_MAG_FILTER = 0x2800" "\n"
"rl.RL_TEXTURE_MIN_FILTER = 0x2801" "\n"
"rl.RL_TEXTURE_FILTER_NEAREST = 0x2600" "\n"
"rl.RL_TEXTURE_FILTER_LINEAR = 0x2601" "\n"
"rl.RL_TEXTURE_FILTER_MIP_NEAREST = 0x2700" "\n"
"rl.RL_TEXTURE_FILTER_NEAREST_MIP_LINEAR = 0x2702" "\n"
"rl.RL_TEXTURE_FILTER_LINEAR_MIP_NEAREST = 0x2701" "\n"
"rl.RL_TEXTURE_FILTER_MIP_LINEAR = 0x2703" "\n"
"rl.RL_TEXTURE_FILTER_ANISOTROPIC = 0x3000" "\n"
"rl.RL_TEXTURE_MIPMAP_BIAS_RATIO = 0x4000" "\n"
"rl.RL_TEXTURE_WRAP_REPEAT = 0x2901" "\n"
"rl.RL_TEXTURE_WRAP_CLAMP = 0x812F" "\n"
"rl.RL_TEXTURE_WRAP_MIRROR_REPEAT = 0x8370" "\n"
"rl.RL_TEXTURE_WRAP_MIRROR_CLAMP = 0x8742" "\n"
"" "\n"
"rl.RL_MODELVIEW = 0x1700" "\n"
"rl.RL_PROJECTION = 0x1701" "\n"
"rl.RL_TEXTURE = 0x1702" "\n"
"rl.RL_LINES = 0x0001" "\n"
"rl.RL_TRIANGLES = 0x0004" "\n"
"rl.RL_QUADS = 0x0007" "\n"
"" "\n"
"rl.RL_UNSIGNED_BYTE = 0x1401" "\n"
"rl.RL_FLOAT = 0x1406" "\n"
"" "\n"
"rl.RL_STREAM_DRAW = 0x88E0" "\n"
"rl.RL_STREAM_READ = 0x88E1" "\n"
"rl.RL_STREAM_COPY = 0x88E2" "\n"
"rl.RL_STATIC_DRAW = 0x88E4" "\n"
"rl.RL_STATIC_READ = 0x88E5" "\n"
"rl.RL_STATIC_COPY = 0x88E6" "\n"
"rl.RL_DYNAMIC_DRAW = 0x88E8" "\n"
"rl.RL_DYNAMIC_READ = 0x88E9" "\n"
"rl.RL_DYNAMIC_COPY = 0x88EA" "\n"
"" "\n"
"rl.RL_FRAGMENT_SHADER = 0x8B30" "\n"
"rl.RL_VERTEX_SHADER = 0x8B31" "\n"
"rl.RL_COMPUTE_SHADER = 0x91B9" "\n"
"" "\n"
"rl.RL_ZERO = 0" "\n"
"rl.RL_ONE = 1" "\n"
"rl.RL_SRC_COLOR = 0x0300" "\n"
"rl.RL_ONE_MINUS_SRC_COLOR = 0x0301" "\n"
"rl.RL_SRC_ALPHA = 0x0302" "\n"
"rl.RL_ONE_MINUS_SRC_ALPHA = 0x0303" "\n"
"rl.RL_DST_ALPHA = 0x0304" "\n"
"rl.RL_ONE_MINUS_DST_ALPHA = 0x0305" "\n"
"rl.RL_DST_COLOR = 0x0306" "\n"
"rl.RL_ONE_MINUS_DST_COLOR = 0x0307" "\n"
"rl.RL_SRC_ALPHA_SATURATE = 0x0308" "\n"
"rl.RL_CONSTANT_COLOR = 0x8001" "\n"
"rl.RL_ONE_MINUS_CONSTANT_COLOR = 0x8002" "\n"
"rl.RL_CONSTANT_ALPHA = 0x8003" "\n"
"rl.RL_ONE_MINUS_CONSTANT_ALPHA = 0x8004" "\n"
"rl.RL_FUNC_ADD = 0x8006" "\n"
"rl.RL_MIN = 0x8007" "\n"
"rl.RL_MAX = 0x8008" "\n"
"rl.RL_FUNC_SUBTRACT = 0x800A" "\n"
"rl.RL_FUNC_REVERSE_SUBTRACT = 0x800B" "\n"
"rl.RL_BLEND_EQUATION = 0x8009" "\n"
"rl.RL_BLEND_EQUATION_RGB = 0x8009" "\n"
"rl.RL_BLEND_EQUATION_ALPHA = 0x883D" "\n"
"rl.RL_BLEND_DST_RGB = 0x80C8" "\n"
"rl.RL_BLEND_SRC_RGB = 0x80C9" "\n"
"rl.RL_BLEND_DST_ALPHA = 0x80CA" "\n"
"rl.RL_BLEND_SRC_ALPHA = 0x80CB" "\n"
"rl.RL_BLEND_COLOR = 0x8005" "\n"
"" "\n"
"-- Physac cdef" "\n"
"ffi.cdef [[" "\n"
"  typedef enum PhysicsShapeType { PHYSICS_CIRCLE = 0, PHYSICS_POLYGON } PhysicsShapeType;" "\n"
"  typedef struct PhysicsBodyData *PhysicsBody;" "\n"
"" "\n"
"  typedef struct Matrix2x2 {" "\n"
"    float m00;" "\n"
"    float m01;" "\n"
"    float m10;" "\n"
"    float m11;" "\n"
"  } Matrix2x2;" "\n"
"" "\n"
"  typedef struct PhysicsVertexData {" "\n"
"    unsigned int vertexCount;" "\n"
"    Vector2 positions[24];" "\n"
"    Vector2 normals[24];" "\n"
"} PhysicsVertexData;" "\n"
"" "\n"
"  typedef struct PhysicsShape {" "\n"
"    PhysicsShapeType type;" "\n"
"    PhysicsBody body;" "\n"
"    PhysicsVertexData vertexData;" "\n"
"    float radius;" "\n"
"    Matrix2x2 transform;" "\n"
"  } PhysicsShape;" "\n"
"" "\n"
"  typedef struct PhysicsBodyData {" "\n"
"    unsigned int id;" "\n"
"    bool enabled;" "\n"
"    Vector2 position;" "\n"
"    Vector2 velocity;" "\n"
"    Vector2 force;" "\n"
"    float angularVelocity;" "\n"
"    float torque;" "\n"
"    float orient;" "\n"
"    float inertia;" "\n"
"    float inverseInertia;" "\n"
"    float mass;" "\n"
"    float inverseMass;" "\n"
"    float staticFriction;" "\n"
"    float dynamicFriction;" "\n"
"    float restitution;" "\n"
"    bool useGravity;" "\n"
"    bool isGrounded;" "\n"
"    bool freezeOrient;" "\n"
"    PhysicsShape shape;" "\n"
"  } PhysicsBodyData;" "\n"
"" "\n"
"  typedef struct PhysicsManifoldData {" "\n"
"    unsigned int id;" "\n"
"    PhysicsBody bodyA;" "\n"
"    PhysicsBody bodyB;" "\n"
"    float penetration;" "\n"
"    Vector2 normal;" "\n"
"    Vector2 contacts[2];" "\n"
"    unsigned int contactsCount;" "\n"
"    float restitution;" "\n"
"    float dynamicFriction;" "\n"
"    float staticFriction;" "\n"
"  } PhysicsManifoldData, *PhysicsManifold;" "\n"
"]]" "\n"
"" "\n"
"-- gestures cdef" "\n"
"ffi.cdef [[" "\n"
"  typedef enum { " "\n"
"    TOUCH_ACTION_UP = 0, " "\n"
"    TOUCH_ACTION_DOWN, " "\n"
"    TOUCH_ACTION_MOVE," "\n"
"    TOUCH_ACTION_CANCEL" "\n"
"  } TouchAction;" "\n"
"" "\n"
"  typedef struct {" "\n"
"    int touchAction;" "\n"
"    int pointCount;" "\n"
"    int pointerId[8]; // CONST" "\n"
"    Vector2 position[8]; // CONST" "\n"
"  } GestureEvent;" "\n"
"]]" "\n"
"" "\n"
"-- raygui cdef" "\n"
"ffi.cdef [[" "\n"
"  typedef struct GuiStyleProp {" "\n"
"    unsigned short controlId;" "\n"
"    unsigned short propertyId;" "\n"
"    int propertyValue;" "\n"
"  } GuiStyleProp;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GUI_STATE_NORMAL = 0," "\n"
"    GUI_STATE_FOCUSED," "\n"
"    GUI_STATE_PRESSED," "\n"
"    GUI_STATE_DISABLED," "\n"
"  } GuiControlState;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GUI_TEXT_ALIGN_LEFT = 0," "\n"
"    GUI_TEXT_ALIGN_CENTER," "\n"
"    GUI_TEXT_ALIGN_RIGHT," "\n"
"  } GuiTextAlignment;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXT_ALIGN_TOP = 0," "\n"
"    TEXT_ALIGN_MIDDLE," "\n"
"    TEXT_ALIGN_BOTTOM" "\n"
"  } GuiTextAlignmentVertical;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXT_WRAP_NONE = 0," "\n"
"    TEXT_WRAP_CHAR," "\n"
"    TEXT_WRAP_WORD" "\n"
"  } GuiTextWrapMode;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    DEFAULT = 0," "\n"
"    LABEL," "\n"
"    BUTTON," "\n"
"    TOGGLE," "\n"
"    SLIDER," "\n"
"    PROGRESSBAR," "\n"
"    CHECKBOX," "\n"
"    COMBOBOX," "\n"
"    DROPDOWNBOX," "\n"
"    TEXTBOX," "\n"
"    VALUEBOX," "\n"
"    SPINNER," "\n"
"    LISTVIEW," "\n"
"    COLORPICKER," "\n"
"    SCROLLBAR," "\n"
"    STATUSBAR" "\n"
"  } GuiControl;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    BORDER_COLOR_NORMAL = 0," "\n"
"    BASE_COLOR_NORMAL," "\n"
"    TEXT_COLOR_NORMAL," "\n"
"    BORDER_COLOR_FOCUSED," "\n"
"    BASE_COLOR_FOCUSED," "\n"
"    TEXT_COLOR_FOCUSED," "\n"
"    BORDER_COLOR_PRESSED," "\n"
"    BASE_COLOR_PRESSED," "\n"
"    TEXT_COLOR_PRESSED," "\n"
"    BORDER_COLOR_DISABLED," "\n"
"    BASE_COLOR_DISABLED," "\n"
"    TEXT_COLOR_DISABLED," "\n"
"    BORDER_WIDTH," "\n"
"    TEXT_PADDING," "\n"
"    TEXT_ALIGNMENT," "\n"
"  } GuiControlProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXT_SIZE = 16," "\n"
"    TEXT_SPACING," "\n"
"    LINE_COLOR," "\n"
"    BACKGROUND_COLOR," "\n"
"    TEXT_LINE_SPACING," "\n"
"    TEXT_ALIGNMENT_VERTICAL," "\n"
"    TEXT_WRAP_MODE" "\n"
"  } GuiDefaultProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GROUP_PADDING = 16," "\n"
"  } GuiToggleProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SLIDER_WIDTH = 16," "\n"
"    SLIDER_PADDING" "\n"
"  } GuiSliderProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    PROGRESS_PADDING = 16," "\n"
"  } GuiProgressBarProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    ARROWS_SIZE = 16," "\n"
"    ARROWS_VISIBLE," "\n"
"    SCROLL_SLIDER_PADDING," "\n"
"    SCROLL_SLIDER_SIZE," "\n"
"    SCROLL_PADDING," "\n"
"    SCROLL_SPEED," "\n"
"  } GuiScrollBarProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    CHECK_PADDING = 16" "\n"
"  } GuiCheckBoxProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    COMBO_BUTTON_WIDTH = 16," "\n"
"    COMBO_BUTTON_PADDING" "\n"
"  } GuiComboBoxProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    ARROW_PADDING = 16," "\n"
"    DROPDOWN_ITEMS_SPACING" "\n"
"  } GuiDropdownBoxProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    TEXT_READONLY = 16" "\n"
"  } GuiTextBoxProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SPIN_BUTTON_WIDTH = 16," "\n"
"    SPIN_BUTTON_SPACING," "\n"
"  } GuiSpinnerProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    SCROLLBAR_LEFT_SIDE = 0," "\n"
"    SCROLLBAR_RIGHT_SIDE" "\n"
"  } GuiScrollBarSide;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    LIST_ITEMS_HEIGHT = 16," "\n"
"    LIST_ITEMS_SPACING," "\n"
"    SCROLLBAR_WIDTH," "\n"
"    SCROLLBAR_SIDE," "\n"
"  } GuiListViewProperty;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    COLOR_SELECTOR_SIZE = 16," "\n"
"    HUEBAR_WIDTH," "\n"
"    HUEBAR_PADDING," "\n"
"    HUEBAR_SELECTOR_HEIGHT," "\n"
"    HUEBAR_SELECTOR_OVERFLOW" "\n"
"  } GuiColorPickerProperty;" "\n"
"" "\n"
"  typedef struct GuiTextBoxState {" "\n"
"    int cursor;" "\n"
"    int start;" "\n"
"    int index;" "\n"
"    int select;" "\n"
"  } GuiTextBoxState;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    ICON_NONE = 0," "\n"
"    ICON_FOLDER_FILE_OPEN = 1," "\n"
"    ICON_FILE_SAVE_CLASSIC = 2," "\n"
"    ICON_FOLDER_OPEN = 3," "\n"
"    ICON_FOLDER_SAVE = 4," "\n"
"    ICON_FILE_OPEN = 5," "\n"
"    ICON_FILE_SAVE = 6," "\n"
"    ICON_FILE_EXPORT = 7," "\n"
"    ICON_FILE_ADD = 8," "\n"
"    ICON_FILE_DELETE = 9," "\n"
"    ICON_FILETYPE_TEXT = 10," "\n"
"    ICON_FILETYPE_AUDIO = 11," "\n"
"    ICON_FILETYPE_IMAGE = 12," "\n"
"    ICON_FILETYPE_PLAY = 13," "\n"
"    ICON_FILETYPE_VIDEO = 14," "\n"
"    ICON_FILETYPE_INFO = 15," "\n"
"    ICON_FILE_COPY = 16," "\n"
"    ICON_FILE_CUT = 17," "\n"
"    ICON_FILE_PASTE = 18," "\n"
"    ICON_CURSOR_HAND = 19," "\n"
"    ICON_CURSOR_POINTER = 20," "\n"
"    ICON_CURSOR_CLASSIC = 21," "\n"
"    ICON_PENCIL = 22," "\n"
"    ICON_PENCIL_BIG = 23," "\n"
"    ICON_BRUSH_CLASSIC = 24," "\n"
"    ICON_BRUSH_PAINTER = 25," "\n"
"    ICON_WATER_DROP = 26," "\n"
"    ICON_COLOR_PICKER = 27," "\n"
"    ICON_RUBBER = 28," "\n"
"    ICON_COLOR_BUCKET = 29," "\n"
"    ICON_TEXT_T = 30," "\n"
"    ICON_TEXT_A = 31," "\n"
"    ICON_SCALE = 32," "\n"
"    ICON_RESIZE = 33," "\n"
"    ICON_FILTER_POINT = 34," "\n"
"    ICON_FILTER_BILINEAR = 35," "\n"
"    ICON_CROP = 36," "\n"
"    ICON_CROP_ALPHA = 37," "\n"
"    ICON_SQUARE_TOGGLE = 38," "\n"
"    ICON_SYMMETRY = 39," "\n"
"    ICON_SYMMETRY_HORIZONTAL = 40," "\n"
"    ICON_SYMMETRY_VERTICAL = 41," "\n"
"    ICON_LENS = 42," "\n"
"    ICON_LENS_BIG = 43," "\n"
"    ICON_EYE_ON = 44," "\n"
"    ICON_EYE_OFF = 45," "\n"
"    ICON_FILTER_TOP = 46," "\n"
"    ICON_FILTER = 47," "\n"
"    ICON_TARGET_POINT = 48," "\n"
"    ICON_TARGET_SMALL = 49," "\n"
"    ICON_TARGET_BIG = 50," "\n"
"    ICON_TARGET_MOVE = 51," "\n"
"    ICON_CURSOR_MOVE = 52," "\n"
"    ICON_CURSOR_SCALE = 53," "\n"
"    ICON_CURSOR_SCALE_RIGHT = 54," "\n"
"    ICON_CURSOR_SCALE_LEFT = 55," "\n"
"    ICON_UNDO = 56," "\n"
"    ICON_REDO = 57," "\n"
"    ICON_REREDO = 58," "\n"
"    ICON_MUTATE = 59," "\n"
"    ICON_ROTATE = 60," "\n"
"    ICON_REPEAT = 61," "\n"
"    ICON_SHUFFLE = 62," "\n"
"    ICON_EMPTYBOX = 63," "\n"
"    ICON_TARGET = 64," "\n"
"    ICON_TARGET_SMALL_FILL = 65," "\n"
"    ICON_TARGET_BIG_FILL = 66," "\n"
"    ICON_TARGET_MOVE_FILL = 67," "\n"
"    ICON_CURSOR_MOVE_FILL = 68," "\n"
"    ICON_CURSOR_SCALE_FILL = 69," "\n"
"    ICON_CURSOR_SCALE_RIGHT_FILL = 70," "\n"
"    ICON_CURSOR_SCALE_LEFT_FILL = 71," "\n"
"    ICON_UNDO_FILL = 72," "\n"
"    ICON_REDO_FILL = 73," "\n"
"    ICON_REREDO_FILL = 74," "\n"
"    ICON_MUTATE_FILL = 75," "\n"
"    ICON_ROTATE_FILL = 76," "\n"
"    ICON_REPEAT_FILL = 77," "\n"
"    ICON_SHUFFLE_FILL = 78," "\n"
"    ICON_EMPTYBOX_SMALL = 79," "\n"
"    ICON_BOX = 80," "\n"
"    ICON_BOX_TOP = 81," "\n"
"    ICON_BOX_TOP_RIGHT = 82," "\n"
"    ICON_BOX_RIGHT = 83," "\n"
"    ICON_BOX_BOTTOM_RIGHT = 84," "\n"
"    ICON_BOX_BOTTOM = 85," "\n"
"    ICON_BOX_BOTTOM_LEFT = 86," "\n"
"    ICON_BOX_LEFT = 87," "\n"
"    ICON_BOX_TOP_LEFT = 88," "\n"
"    ICON_BOX_CENTER = 89," "\n"
"    ICON_BOX_CIRCLE_MASK = 90," "\n"
"    ICON_POT = 91," "\n"
"    ICON_ALPHA_MULTIPLY = 92," "\n"
"    ICON_ALPHA_CLEAR = 93," "\n"
"    ICON_DITHERING = 94," "\n"
"    ICON_MIPMAPS = 95," "\n"
"    ICON_BOX_GRID = 96," "\n"
"    ICON_GRID = 97," "\n"
"    ICON_BOX_CORNERS_SMALL = 98," "\n"
"    ICON_BOX_CORNERS_BIG = 99," "\n"
"    ICON_FOUR_BOXES = 100," "\n"
"    ICON_GRID_FILL = 101," "\n"
"    ICON_BOX_MULTISIZE = 102," "\n"
"    ICON_ZOOM_SMALL = 103," "\n"
"    ICON_ZOOM_MEDIUM = 104," "\n"
"    ICON_ZOOM_BIG = 105," "\n"
"    ICON_ZOOM_ALL = 106," "\n"
"    ICON_ZOOM_CENTER = 107," "\n"
"    ICON_BOX_DOTS_SMALL = 108," "\n"
"    ICON_BOX_DOTS_BIG = 109," "\n"
"    ICON_BOX_CONCENTRIC = 110," "\n"
"    ICON_BOX_GRID_BIG = 111," "\n"
"    ICON_OK_TICK = 112," "\n"
"    ICON_CROSS = 113," "\n"
"    ICON_ARROW_LEFT = 114," "\n"
"    ICON_ARROW_RIGHT = 115," "\n"
"    ICON_ARROW_DOWN = 116," "\n"
"    ICON_ARROW_UP = 117," "\n"
"    ICON_ARROW_LEFT_FILL = 118," "\n"
"    ICON_ARROW_RIGHT_FILL = 119," "\n"
"    ICON_ARROW_DOWN_FILL = 120," "\n"
"    ICON_ARROW_UP_FILL = 121," "\n"
"    ICON_AUDIO = 122," "\n"
"    ICON_FX = 123," "\n"
"    ICON_WAVE = 124," "\n"
"    ICON_WAVE_SINUS = 125," "\n"
"    ICON_WAVE_SQUARE = 126," "\n"
"    ICON_WAVE_TRIANGULAR = 127," "\n"
"    ICON_CROSS_SMALL = 128," "\n"
"    ICON_PLAYER_PREVIOUS = 129," "\n"
"    ICON_PLAYER_PLAY_BACK = 130," "\n"
"    ICON_PLAYER_PLAY = 131," "\n"
"    ICON_PLAYER_PAUSE = 132," "\n"
"    ICON_PLAYER_STOP = 133," "\n"
"    ICON_PLAYER_NEXT = 134," "\n"
"    ICON_PLAYER_RECORD = 135," "\n"
"    ICON_MAGNET = 136," "\n"
"    ICON_LOCK_CLOSE = 137," "\n"
"    ICON_LOCK_OPEN = 138," "\n"
"    ICON_CLOCK = 139," "\n"
"    ICON_TOOLS = 140," "\n"
"    ICON_GEAR = 141," "\n"
"    ICON_GEAR_BIG = 142," "\n"
"    ICON_BIN = 143," "\n"
"    ICON_HAND_POINTER = 144," "\n"
"    ICON_LASER = 145," "\n"
"    ICON_COIN = 146," "\n"
"    ICON_EXPLOSION = 147," "\n"
"    ICON_1UP = 148," "\n"
"    ICON_PLAYER = 149," "\n"
"    ICON_PLAYER_JUMP = 150," "\n"
"    ICON_KEY = 151," "\n"
"    ICON_DEMON = 152," "\n"
"    ICON_TEXT_POPUP = 153," "\n"
"    ICON_GEAR_EX = 154," "\n"
"    ICON_CRACK = 155," "\n"
"    ICON_CRACK_POINTS = 156," "\n"
"    ICON_STAR = 157," "\n"
"    ICON_DOOR = 158," "\n"
"    ICON_EXIT = 159," "\n"
"    ICON_MODE_2D = 160," "\n"
"    ICON_MODE_3D = 161," "\n"
"    ICON_CUBE = 162," "\n"
"    ICON_CUBE_FACE_TOP = 163," "\n"
"    ICON_CUBE_FACE_LEFT = 164," "\n"
"    ICON_CUBE_FACE_FRONT = 165," "\n"
"    ICON_CUBE_FACE_BOTTOM = 166," "\n"
"    ICON_CUBE_FACE_RIGHT = 167," "\n"
"    ICON_CUBE_FACE_BACK = 168," "\n"
"    ICON_CAMERA = 169," "\n"
"    ICON_SPECIAL = 170," "\n"
"    ICON_LINK_NET = 171," "\n"
"    ICON_LINK_BOXES = 172," "\n"
"    ICON_LINK_MULTI = 173," "\n"
"    ICON_LINK = 174," "\n"
"    ICON_LINK_BROKE = 175," "\n"
"    ICON_TEXT_NOTES = 176," "\n"
"    ICON_NOTEBOOK = 177," "\n"
"    ICON_SUITCASE = 178," "\n"
"    ICON_SUITCASE_ZIP = 179," "\n"
"    ICON_MAILBOX = 180," "\n"
"    ICON_MONITOR = 181," "\n"
"    ICON_PRINTER = 182," "\n"
"    ICON_PHOTO_CAMERA = 183," "\n"
"    ICON_PHOTO_CAMERA_FLASH = 184," "\n"
"    ICON_HOUSE = 185," "\n"
"    ICON_HEART = 186," "\n"
"    ICON_CORNER = 187," "\n"
"    ICON_VERTICAL_BARS = 188," "\n"
"    ICON_VERTICAL_BARS_FILL = 189," "\n"
"    ICON_LIFE_BARS = 190," "\n"
"    ICON_INFO = 191," "\n"
"    ICON_CROSSLINE = 192," "\n"
"    ICON_HELP = 193," "\n"
"    ICON_FILETYPE_ALPHA = 194," "\n"
"    ICON_FILETYPE_HOME = 195," "\n"
"    ICON_LAYERS_VISIBLE = 196," "\n"
"    ICON_LAYERS = 197," "\n"
"    ICON_WINDOW = 198," "\n"
"    ICON_HIDPI = 199," "\n"
"    ICON_FILETYPE_BINARY = 200," "\n"
"    ICON_HEX = 201," "\n"
"    ICON_SHIELD = 202," "\n"
"    ICON_FILE_NEW = 203," "\n"
"    ICON_FOLDER_ADD = 204," "\n"
"    ICON_ALARM = 205," "\n"
"    ICON_CPU = 206," "\n"
"    ICON_ROM = 207," "\n"
"    ICON_STEP_OVER = 208," "\n"
"    ICON_STEP_INTO = 209," "\n"
"    ICON_STEP_OUT = 210," "\n"
"    ICON_RESTART = 211," "\n"
"    ICON_BREAKPOINT_ON = 212," "\n"
"    ICON_BREAKPOINT_OFF = 213," "\n"
"    ICON_BURGER_MENU = 214," "\n"
"    ICON_CASE_SENSITIVE = 215," "\n"
"    ICON_REG_EXP = 216," "\n"
"    ICON_FOLDER = 217," "\n"
"    ICON_FILE = 218," "\n"
"    ICON_219 = 219," "\n"
"    ICON_220 = 220," "\n"
"    ICON_221 = 221," "\n"
"    ICON_222 = 222," "\n"
"    ICON_223 = 223," "\n"
"    ICON_224 = 224," "\n"
"    ICON_225 = 225," "\n"
"    ICON_226 = 226," "\n"
"    ICON_227 = 227," "\n"
"    ICON_228 = 228," "\n"
"    ICON_229 = 229," "\n"
"    ICON_230 = 230," "\n"
"    ICON_231 = 231," "\n"
"    ICON_232 = 232," "\n"
"    ICON_233 = 233," "\n"
"    ICON_234 = 234," "\n"
"    ICON_235 = 235," "\n"
"    ICON_236 = 236," "\n"
"    ICON_237 = 237," "\n"
"    ICON_238 = 238," "\n"
"    ICON_239 = 239," "\n"
"    ICON_240 = 240," "\n"
"    ICON_241 = 241," "\n"
"    ICON_242 = 242," "\n"
"    ICON_243 = 243," "\n"
"    ICON_244 = 244," "\n"
"    ICON_245 = 245," "\n"
"    ICON_246 = 246," "\n"
"    ICON_247 = 247," "\n"
"    ICON_248 = 248," "\n"
"    ICON_249 = 249," "\n"
"    ICON_250 = 250," "\n"
"    ICON_251 = 251," "\n"
"    ICON_252 = 252," "\n"
"    ICON_253 = 253," "\n"
"    ICON_254 = 254," "\n"
"    ICON_255 = 255," "\n"
"  } GuiIconName;" "\n"
"]]" "\n"
"" "\n"
"-- Load bind entry" "\n"
"ffi.cdef [[" "\n"
"  struct raylua_bind_entry {" "\n"
"    const char *name;" "\n"
"    const char *proto;" "\n"
"    void *ptr;" "\n"
"  };" "\n"
"]]" "\n"
"" "\n"
"do" "\n"
"  local entries = ffi.cast(\"struct raylua_bind_entry *\", raylua.bind_entries)" "\n"
"  local i = ffi.new(\"size_t\", 0)" "\n"
"  local NULL = ffi.new(\"void *\", nil)" "\n"
"" "\n"
"  print \"RAYLUA: Loading FFI binding entries.\"" "\n"
"" "\n"
"  while entries[i].name ~= NULL do" "\n"
"    local name, proto = ffi.string(entries[i].name), ffi.string(entries[i].proto)" "\n"
"" "\n"
"    if rl[name] then" "\n"
"      print(\"RAYLUA: Warn: Duplicated FFI entry : \" .. name)" "\n"
"    end" "\n"
"" "\n"
"    rl[name] = ffi.cast(proto, entries[i].ptr)" "\n"
"    i = i + 1" "\n"
"  end" "\n"
"" "\n"
"  print(\"RAYLUA: Loaded \" .. tonumber(i) .. \" FFI entries.\")" "\n"
"end" "\n"
"" "\n"
"-- colors" "\n"
"local function new_color(r, g, b, a)" "\n"
"  return ffi.new(\"Color\", r, g, b, a)" "\n"
"end" "\n"
"" "\n"
"rl.LIGHTGRAY = new_color(200, 200, 200, 255)" "\n"
"rl.GRAY = new_color(130, 130, 130, 255)" "\n"
"rl.DARKGRAY = new_color(80, 80, 80, 255)" "\n"
"rl.YELLOW = new_color(253, 249, 0, 255)" "\n"
"rl.GOLD = new_color(255, 203, 0, 255)" "\n"
"rl.ORANGE = new_color(255, 161, 0, 255)" "\n"
"rl.PINK = new_color(255, 109, 194, 255)" "\n"
"rl.RED = new_color(230, 41, 55, 255)" "\n"
"rl.MAROON = new_color(190, 33, 55, 255)" "\n"
"rl.GREEN = new_color(0, 228, 48, 255)" "\n"
"rl.LIME = new_color(0, 158, 47, 255)" "\n"
"rl.DARKGREEN = new_color(0, 117, 44, 255)" "\n"
"rl.SKYBLUE = new_color(102, 191, 255, 255)" "\n"
"rl.BLUE = new_color(0, 121, 241, 255)" "\n"
"rl.DARKBLUE = new_color(0, 82, 172, 255)" "\n"
"rl.PURPLE = new_color(200, 122, 255, 255)" "\n"
"rl.VIOLET = new_color(135, 60, 190, 255)" "\n"
"rl.DARKPURPLE = new_color(112, 31, 126, 255)" "\n"
"rl.BEIGE = new_color(211, 176, 131, 255)" "\n"
"rl.BROWN = new_color(127, 106, 79, 255)" "\n"
"rl.DARKBROWN = new_color(76, 63, 47, 255)" "\n"
"rl.WHITE = new_color(255, 255, 255, 255)" "\n"
"rl.BLACK = new_color(0, 0, 0, 255)" "\n"
"rl.BLANK = new_color(0, 0, 0, 0)" "\n"
"rl.MAGENTA = new_color(255, 0, 255, 255)" "\n"
"rl.RAYWHITE = new_color(245, 245, 245, 255)" "\n"
"" "\n"
"rl.SHADER_LOC_MAP_DIFFUSE = C.SHADER_LOC_MAP_ALBEDO" "\n"
"rl.SHADER_LOC_MAP_SPECULAR = C.SHADER_LOC_MAP_METALNESS" "\n"
"rl.MATERIAL_MAP_DIFFUSE = C.MATERIAL_MAP_ALBEDO" "\n"
"rl.MATERIAL_MAP_SPECULAR = C.MATERIAL_MAP_METALNESS" "\n"
"" "\n"
"function rl.ref(obj)" "\n"
"  return ffi.cast(ffi.typeof(\"$ *\", obj), obj)" "\n"
"end" "\n"
"" "\n"
"rl.new = ffi.new" "\n"
"" "\n"
"rl.__index = function (self, key)" "\n"
"  return C[key]" "\n"
"end" "\n"
"" "\n"
"rl.__newindex = function ()" "\n"
"  error \"rl table is readonly\"" "\n"
"end" "\n"
"" "\n"
"_G.rl = rl" "\n"
"--[[" "\n"
"  Copyright (C) 2020 Astie Teddy" "\n"
"" "\n"
"  Permission to use, copy, modify, and/or distribute this software for any" "\n"
"  purpose with or without fee is hereby granted, provided that the above" "\n"
"  copyright notice and this permission notice appear in all copies." "\n"
"" "\n"
"  THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES" "\n"
"  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF" "\n"
"  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR" "\n"
"  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES" "\n"
"  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION" "\n"
"  OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN" "\n"
"  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE." "\n"
"]]" "\n"
"" "\n"
"local new = ffi.new" "\n"
"" "\n"
"-- Allow rl modification" "\n"
"local old_newindex = rl.__newindex" "\n"
"rl.__newindex = nil" "\n"
"" "\n"
"-- Load*() wrappers." "\n"
"if raylua.loadfile then" "\n"
"  local LoadMusicStream = rl.LoadMusicStream" "\n"
"  function rl.LoadMusicStream(path)" "\n"
"    local f, err = raylua.loadfile(path)" "\n"
"" "\n"
"    if f then" "\n"
"      local ext = \".\" .. path:gsub(\".+%.\", \"\")" "\n"
"" "\n"
"      return rl.LoadMusicStreamFromMemory(ext, ffi.cast(\"void *\", f), #f)" "\n"
"    else" "\n"
"      print((\"RAYLUA: %s\"):format(err))" "\n"
"      return LoadMusicStream(path)" "\n"
"    end" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"-- math metamethods" "\n"
"ffi.metatype(\"Vector2\", {" "\n"
"  __add = function (a, b)" "\n"
"    if ffi.istype(\"Vector2\", b) then" "\n"
"      return new(\"Vector2\", a.x + b.x, a.y + b.y)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __sub = function (a, b)" "\n"
"    if ffi.istype(\"Vector2\", b) then" "\n"
"      return new(\"Vector2\", a.x - b.x, a.y - b.y)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __unm = function (a)" "\n"
"    return new(\"Vector2\", -a.x, -a.y)" "\n"
"  end," "\n"
"  __len = function (a)" "\n"
"    return math.sqrt(a.x * a.x + a.y * a.y)" "\n"
"  end," "\n"
"  __mul = function (a, b)" "\n"
"    if type(a) == \"number\" then" "\n"
"      -- swap if a is a number (a * vector)" "\n"
"      a, b = b, a" "\n"
"    end" "\n"
"" "\n"
"    if ffi.istype(\"Vector2\", b) then -- dot product" "\n"
"      return a.x * b.x + a.y * b.y" "\n"
"    elseif type(b) == \"number\" then" "\n"
"      return new(\"Vector2\", a.x * b, a.y * b)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __div = function (a, b)" "\n"
"    if type(b) == \"number\" then" "\n"
"      return new(\"Vector2\", a.x / b, a.y / b)" "\n"
"    else" "\n"
"      error \"Invalid operation\"" "\n"
"    end" "\n"
"  end," "\n"
"  __tostring = function (a)" "\n"
"    return string.format(\"Vector2: (%g %g)\", a.x, a.y)" "\n"
"  end" "\n"
"})" "\n"
"" "\n"
"ffi.metatype(\"Vector3\", {" "\n"
"  __add = function (a, b)" "\n"
"    if ffi.istype(\"Vector3\", b) then" "\n"
"      return new(\"Vector3\", a.x + b.x, a.y + b.y, a.z + b.z)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __sub = function (a, b)" "\n"
"    if ffi.istype(\"Vector3\", b) then" "\n"
"      return new(\"Vector3\", a.x - b.x, a.y - b.y, a.z - b.z)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __unm = function (a)" "\n"
"    return new(\"Vector3\", -a.x, -a.y, -a.z)" "\n"
"  end," "\n"
"  __len = function (a)" "\n"
"    return math.sqrt(a.x * a.x + a.y * a.y + a.z * a.z)" "\n"
"  end," "\n"
"  __mul = function (a, b)" "\n"
"    if type(a) == \"number\" then" "\n"
"      -- swap if a is a number (a * vector)" "\n"
"      a, b = b, a" "\n"
"    end" "\n"
"" "\n"
"    if ffi.istype(\"Vector3\", b) then -- dot product" "\n"
"      return a.x * b.x + a.y * b.y + a.z * b.z" "\n"
"    elseif type(b) == \"number\" then" "\n"
"      return new(\"Vector3\", a.x * b, a.y * b, a.z * b)" "\n"
"    else" "\n"
"      error \"Invalid operation.\"" "\n"
"    end" "\n"
"  end," "\n"
"  __div = function (a, b)" "\n"
"    if type(b) == \"number\" then" "\n"
"      return new(\"Vector3\", a.x / b, a.y / b, a.z / b)" "\n"
"    else" "\n"
"      error \"Invalid operation\"" "\n"
"    end" "\n"
"  end," "\n"
"  __tostring = function (a)" "\n"
"    return string.format(\"Vector3: (%g %g %g)\", a.x, a.y, a.z)" "\n"
"  end" "\n"
"})" "\n"
"" "\n"
"-- TODO: Matrix and Quaternion" "\n"
"" "\n"
"-- Easing functions" "\n"
"function rl.EaseLinearNone(t, b, c, d)" "\n"
"  return c * t / d + b" "\n"
"end" "\n"
"" "\n"
"rl.EaseLinearIn = rl.EaseLinearNone" "\n"
"rl.EaseLinearOut = rl.EaseLinearNone" "\n"
"rl.EaseLinearInOut = rl.EaseLinearNone" "\n"
"" "\n"
"function rl.EaseSineIn(t, b, c, d)" "\n"
"  return -c * math.cos(t / d * (math.pi / 2.0)) + c + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseSineOut(t, b, c, d)" "\n"
"  return c * math.sin(t / d * (math.pi / 2.0)) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseSineInOut(t, b, c, d)" "\n"
"  return -c / 2.0 * (math.cos(math.pi * t / d) - 1.0) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCircIn(t, b, c, d)" "\n"
"  t = t / d" "\n"
"  return -c * (math.sqrt(1.0 - t * t) - 1.0) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCircOut(t, b, c, d)" "\n"
"  t = t / d - 1.0" "\n"
"  return c * math.sqrt(1.0 - t * t) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCircInOut(t, b, c, d)" "\n"
"  t = t / (d / 2.0)" "\n"
"" "\n"
"  if t < 1.0 then" "\n"
"    return -c / 2.0 * (math.sqrt(1.0 - t * t) - 1.0) + b" "\n"
"  else" "\n"
"    t = t - 2.0" "\n"
"    return c / 2.0 * (math.sqrt(1.0 - t * t) + 1.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCubicIn(t, b, c, d)" "\n"
"  t = t / d" "\n"
"  return c * t * t * t + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCubicOut(t, b, c, d) " "\n"
"  t = t / d - 1.0" "\n"
"  return c * (t * t * t + 1.0) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseCubicInOut(t, b, c, d)" "\n"
"  t = t / (d / 2.0)" "\n"
"" "\n"
"  if t < 1.0 then" "\n"
"    return c / 2.0 * t * t * t + b" "\n"
"  else" "\n"
"    t = t - 2.0" "\n"
"    return c / 2.0 * (t * t * t + 2.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseQuadIn(t, b, c, d)" "\n"
"  t = t / d" "\n"
"  return c * t * t + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseQuadOut(t, b, c, d)" "\n"
"  t = t / d" "\n"
"  return -c * t * (t - 2.0) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseQuadInOut(t, b, c, d)" "\n"
"  t = t / (d / 2.0)" "\n"
"" "\n"
"  if t < 1.0 then" "\n"
"    return ((c / 2) * (t * t)) + b" "\n"
"  else" "\n"
"    return -c / 2.0 * (((t - 1.0) * (t - 3.0)) - 1.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseExpoIn(t, b, c, d)" "\n"
"  if t == 0.0 then" "\n"
"    return b" "\n"
"  else" "\n"
"    return (c * math.pow(2.0, 10.0 * (t/d - 1.0)) + b)" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseExpoOut(t, b, c, d)" "\n"
"  if t == d then" "\n"
"    return b + c" "\n"
"  else" "\n"
"    return c * (math.pow(2.0, -10.0 * t / d) + 1.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseExpoInOut(t, b, c, d)" "\n"
"  if t == 0.0 then" "\n"
"    return b" "\n"
"  elseif t == d then" "\n"
"    return b + c" "\n"
"  end" "\n"
"" "\n"
"  t = t / (d / 2.0)" "\n"
"  if t < 1.0 then" "\n"
"    return c / 2.0 * math.pow(2.0, 10.0 * (t - 1.0)) + b" "\n"
"  else" "\n"
"    return c / 2.0 * (-math.pow(2.0, -10.0 * (t - 1.0)) + 2.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBackIn(t, b, c, d)" "\n"
"  local s = 1.70158" "\n"
"  t = t / d" "\n"
"  return c * t * t * ((s + 1.0) * t - s) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBackOut(t, b, c, d)" "\n"
"  local s = 1.70158" "\n"
"  t = t / d - 1.0" "\n"
"  return c * (t * t * ((s + 1.0) * t + s) + 1.0) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBackInOut(t, b, c, d)" "\n"
"  local s = 1.70158 * 1.525;" "\n"
"  t = t / (d / 2.0)" "\n"
"" "\n"
"  if t < 1.0 then" "\n"
"    return c / 2.0 * (t * t * ((s + 1.0) * t - s)) + b" "\n"
"  else" "\n"
"    t = t - 2.0" "\n"
"    return c / 2.0 * (t * t * ((s + 1.0) * t + s) + 2.0) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBounceOut(t, b, c, d)" "\n"
"  t = t / d" "\n"
"" "\n"
"  if t < 1.0 / 2.75 then" "\n"
"    return c * (7.5625 * t * t) + b" "\n"
"  elseif t < 2.0 / 2.75 then" "\n"
"    t = t - 1.5 / 2.75" "\n"
"    return c * (7.5625 * t * t + 0.75) + b" "\n"
"  elseif t < 2.5 / 2.75 then" "\n"
"    t = t - 2.25 / 2.75" "\n"
"    return c * (7.5625 * t * t + 0.9375) + b" "\n"
"  else" "\n"
"    t = t - 2.625 / 2.75" "\n"
"    return c * (7.5625 * t * t + 0.984375) + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBounceIn(t, b, c, d)" "\n"
"  return (c - rl.EaseBounceOut(d - t, 0.0, c, d) + b)" "\n"
"end" "\n"
"" "\n"
"function rl.EaseBounceInOut(t, b, c, d)" "\n"
"  if t < d / 2.0 then" "\n"
"    return rl.EaseBounceIn(t * 2.0, 0.0, c, d) * 0.5 + b" "\n"
"  else" "\n"
"    return rl.EaseBounceOut(t * 2.0 - d, 0.0, c, d) * 0.5 + c * 0.5 + b" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"function rl.EaseElasticIn(t, b, c, d)" "\n"
"  if t == 0.0 then" "\n"
"    return b" "\n"
"  end" "\n"
"" "\n"
"  t = t / d" "\n"
"  if t == 1.0 then" "\n"
"    return b + c" "\n"
"  end" "\n"
"" "\n"
"  t = t - 1.0" "\n"
"" "\n"
"  local p = d * 0.3" "\n"
"  local a = c" "\n"
"  local s = p / 4.0" "\n"
"  local postFix = a * math.pow(2.0, 10.0 * t)" "\n"
"" "\n"
"  return -(postFix * math.sin((t * d - s) * (2.0 * math.pi) / p)) + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseElasticOut(t, b, c, d)" "\n"
"  if t == 0.0 then" "\n"
"    return b" "\n"
"  end" "\n"
"" "\n"
"  t = t / d" "\n"
"  if t == 1.0 then" "\n"
"    return b + c" "\n"
"  end" "\n"
"" "\n"
"  local p = d * 0.3" "\n"
"  local a = c" "\n"
"  local s = p / 4.0" "\n"
"" "\n"
"  return a * math.pow(2.0,-10.0 * t) * math.sin((t * d - s) * (2.0 * math.pi) / p) + c + b" "\n"
"end" "\n"
"" "\n"
"function rl.EaseElasticInOut(t, b, c, d)" "\n"
"  if t == 0.0 then" "\n"
"    return b" "\n"
"  end" "\n"
"" "\n"
"  t = t / (d / 2.0)" "\n"
"  if t == 2.0 then" "\n"
"    return b + c" "\n"
"  end" "\n"
"" "\n"
"  local p = d * 0.3 * 1.5" "\n"
"  local a = c" "\n"
"  local s = p / 4.0" "\n"
"" "\n"
"  if t < 1.0 then" "\n"
"    t = t - 1" "\n"
"    local postFix = a * math.pow(2.0, 10.0 * t)" "\n"
"    return -0.5 * (postFix * math.sin((t * d - s)*(2.0 * math.pi) / p)) + b" "\n"
"  end" "\n"
"" "\n"
"  t = t - 1.0" "\n"
"  local postFix = a * math.pow(2.0, -10.0 * t)" "\n"
"  return postFix * math.sin((t * d - s) * (2.0 * math.pi) / p) * 0.5 + c + b" "\n"
"end" "\n"
"" "\n"
"-- Revert __newindex" "\n"
"rl.__newindex = old_newindex" "\n"
"--[[" "\n"
"  Copyright (C) 2020 Astie Teddy" "\n"
"" "\n"
"  Permission to use, copy, modify, and/or distribute this software for any" "\n"
"  purpose with or without fee is hereby granted, provided that the above" "\n"
"  copyright notice and this permission notice appear in all copies." "\n"
"" "\n"
"  THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES" "\n"
"  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF" "\n"
"  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR" "\n"
"  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES" "\n"
"  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION" "\n"
"  OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN" "\n"
"  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE." "\n"
"]]" "\n"
"" "\n"
"local load = loadstring" "\n"
"" "\n"
"raylua.version = \"v5.5-dev\"" "\n"
"" "\n"
"function raylua.repl()" "\n"
"  print(\"> raylua \" .. raylua.version .. \" <\")" "\n"
"  print \"Type 'q' to quit.\"" "\n"
"  print \"\"" "\n"
"" "\n"
"  while true do" "\n"
"    io.write \"> \"" "\n"
"    local line = io.read \"l\"" "\n"
"    if line == \"q\" then" "\n"
"      break" "\n"
"    end" "\n"
"" "\n"
"    local f, err = loadstring(line)" "\n"
"" "\n"
"    if f then" "\n"
"      local status, err = pcall(f)" "\n"
"      if not status then" "\n"
"        print(err)" "\n"
"      end" "\n"
"    else" "\n"
"      print(err)" "\n"
"    end" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"package.path = \"?.lua;?/init.lua\"" "\n"
"" "\n"
"if os.getenv \"LUA_PATH\" then" "\n"
"  package.path = package.path .. \";\" .. os.getenv \"LUA_PATH\"" "\n"
"end" "\n"
"" "\n"
"if raylua.loadfile then" "\n"
"  -- Change the second loader to load files using raylua.loadfile" "\n"
"  package.loaders[2] = function (name)" "\n"
"    for path in package.path:gmatch \"([^;]+);?\" do" "\n"
"      name = name:gsub(\"%.\", \"/\")" "\n"
"      path = path:gsub(\"?\", name)" "\n"
"" "\n"
"      local content, err = raylua.loadfile(path)" "\n"
"      if content then" "\n"
"        local f, err = load(content, path)" "\n"
"        assert(f, err)" "\n"
"" "\n"
"        return f" "\n"
"      end" "\n"
"    end" "\n"
"" "\n"
"    return" "\n"
"  end" "\n"
"" "\n"
"  print \"RAYLUA: Load main.lua from payload.\"" "\n"
"" "\n"
"  local f, err = load(raylua.loadfile \"main.lua\", \"main.lua\")" "\n"
"  if f then" "\n"
"    local status, f_err = xpcall(f, debug.traceback)" "\n"
"" "\n"
"    if not status then" "\n"
"      print(f_err)" "\n"
"    end" "\n"
"  else" "\n"
"    print(err)" "\n"
"  end" "\n"
"" "\n"
"  if not raylua.isrepl then" "\n"
"    return" "\n"
"  end" "\n"
"" "\n"
"  -- Keep launching the repl even with `loadfile` defined." "\n"
"end" "\n"
"" "\n"
"if arg and arg[1] then" "\n"
"  local f, err = loadfile(arg[1])" "\n"
"  if f then" "\n"
"    local status, f_err = xpcall(f, debug.traceback)" "\n"
"" "\n"
"    if not status then" "\n"
"      print(f_err)" "\n"
"    end" "\n"
"  else" "\n"
"    print(err)" "\n"
"  end" "\n"
"" "\n"
"  return" "\n"
"end" "\n"
"" "\n"
"if raylua.isrepl then" "\n"
"  print \"RAYLUA: Go to repl.\"" "\n"
"  raylua.repl()" "\n"
"end" "\n"
;